import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:devroute_ai_studio/features/grpc/application/grpc_dynamic_message_codec.dart';
import 'package:devroute_ai_studio/features/grpc/data/grpc_descriptor_loader.dart';
import 'package:devroute_ai_studio/features/grpc/domain/grpc_codec_models.dart';
import 'package:devroute_ai_studio/core/security/secret_masker.dart';
import 'package:fixnum/fixnum.dart';
import 'package:flutter_test/flutter_test.dart';

import 'fixtures/grpc/generated/phase5_test_service.pb.dart';

void main() {
  late GrpcDynamicMessageCodec codec;

  setUpAll(() {
    final bytes = File(
      'test/fixtures/grpc/generated/phase5_test_service.protoset',
    ).readAsBytesSync();
    codec = GrpcDynamicMessageCodec(
      const GrpcDescriptorLoader().load(bytes).registry,
    );
  });

  test('encodes every scalar identically to the generated message', () {
    final input = <String, Object?>{
      'doubleValue': 1.5,
      'floatValue': 2.25,
      'int32Value': -7,
      'int64Value': '-9007199254740992',
      'uint32Value': 4000000000,
      'uint64Value': '18446744073709551615',
      'sint32Value': -8,
      'sint64Value': '-9007199254740993',
      'fixed32Value': 3000000000,
      'fixed64Value': '9007199254740994',
      'sfixed32Value': -9,
      'sfixed64Value': '-9007199254740994',
      'boolValue': true,
      'stringValue': 'hello',
      'bytesValue': base64Encode(<int>[0, 1, 255]),
      'mode': 'TEST_MODE_ACTIVE',
    };
    final original = jsonEncode(input);
    final generated = CodecMessage(
      doubleValue: 1.5,
      floatValue: 2.25,
      int32Value: -7,
      int64Value: Int64.parseInt('-9007199254740992'),
      uint32Value: 4000000000,
      uint64Value: Int64.parseInt('18446744073709551615'),
      sint32Value: -8,
      sint64Value: Int64.parseInt('-9007199254740993'),
      fixed32Value: 3000000000,
      fixed64Value: Int64.parseInt('9007199254740994'),
      sfixed32Value: -9,
      sfixed64Value: Int64.parseInt('-9007199254740994'),
      boolValue: true,
      stringValue: 'hello',
      bytesValue: <int>[0, 1, 255],
      mode: TestMode.TEST_MODE_ACTIVE,
    );

    expect(
      codec.encode('devroute.phase5.test.CodecMessage', input),
      generated.writeToBuffer(),
    );
    expect(jsonEncode(input), original);
  });

  test('encodes nested, packed, map and oneof deterministically', () {
    final first = <String, Object?>{
      'labels': <String, Object?>{'z': 2, 'a': 1},
      'packedValues': <int>[1, 2, 300],
      'nested': <String, Object?>{'name': 'nested'},
      'numericLabels': <String, Object?>{'7': 'seven', '-2': 'minus'},
      'booleanLabels': <String, Object?>{'true': 'yes', 'false': 'no'},
      'first': 'selected',
    };
    final second = <String, Object?>{
      'first': 'selected',
      'nested': <String, Object?>{'name': 'nested'},
      'packedValues': <int>[1, 2, 300],
      'labels': <String, Object?>{'a': 1, 'z': 2},
      'booleanLabels': <String, Object?>{'false': 'no', 'true': 'yes'},
      'numericLabels': <String, Object?>{'-2': 'minus', '7': 'seven'},
    };
    final generated = CodecMessage(
      nested: NestedValue(name: 'nested'),
      packedValues: <int>[1, 2, 300],
      labels: <String, int>{'a': 1, 'z': 2}.entries,
      numericLabels: <int, String>{-2: 'minus', 7: 'seven'}.entries,
      booleanLabels: <bool, String>{false: 'no', true: 'yes'}.entries,
      first: 'selected',
    );

    final firstBytes = codec.encode('devroute.phase5.test.CodecMessage', first);
    expect(
      firstBytes,
      codec.encode('devroute.phase5.test.CodecMessage', second),
    );
    expect(firstBytes, generated.writeToBuffer());
  });

  test('decodes generated bytes with canonical int64 and base64 policy', () {
    final generated = CodecMessage(
      int64Value: Int64.parseInt('-9007199254740992'),
      uint64Value: Int64.parseInt('18446744073709551615'),
      bytesValue: <int>[1, 2, 3],
      mode: TestMode.TEST_MODE_ACTIVE,
      packedValues: <int>[4, 5],
      labels: <String, int>{'region': 7}.entries,
    );
    final decoded =
        codec.decode(
              'devroute.phase5.test.CodecMessage',
              Uint8List.fromList(generated.writeToBuffer()),
            )
            as Map<String, Object?>;

    expect(decoded['int64Value'], '-9007199254740992');
    expect(decoded['uint64Value'], '18446744073709551615');
    expect(decoded['bytesValue'], 'AQID');
    expect(decoded['mode'], 'TEST_MODE_ACTIVE');
    expect(decoded['packedValues'], <int>[4, 5]);
    expect(decoded['labels'], <String, Object?>{'region': 7});
  });

  test('rejects malformed wire and enforces size and item bounds', () {
    expect(
      () => codec.decode(
        'devroute.phase5.test.CodecMessage',
        Uint8List.fromList(<int>[0x72, 0x04, 0x61]),
      ),
      throwsA(isA<GrpcCodecException>()),
    );
    expect(
      () =>
          GrpcDynamicMessageCodec(
            const GrpcDescriptorLoader()
                .load(
                  File(
                    'test/fixtures/grpc/generated/phase5_test_service.protoset',
                  ).readAsBytesSync(),
                )
                .registry,
            maximumMessageBytes: 1,
          ).encode('devroute.phase5.test.CodecMessage', <String, Object?>{
            'stringValue': 'large',
          }),
      throwsA(isA<GrpcCodecException>()),
    );
    expect(
      () =>
          GrpcDynamicMessageCodec(
            const GrpcDescriptorLoader()
                .load(
                  File(
                    'test/fixtures/grpc/generated/phase5_test_service.protoset',
                  ).readAsBytesSync(),
                )
                .registry,
            maximumRepeatedItems: 1,
          ).encode('devroute.phase5.test.CodecMessage', <String, Object?>{
            'packedValues': <int>[1, 2],
          }),
      throwsA(isA<GrpcCodecException>()),
    );
  });

  test('skips unknown fields and preserves unknown enum numbers', () {
    final known = CodecMessage(int32Value: 7).writeToBuffer();
    final withUnknown = Uint8List.fromList(<int>[
      ...known,
      0x98,
      0x06,
      0x01,
      0x80,
      0x01,
      0x63,
    ]);
    final decoded =
        codec.decode('devroute.phase5.test.CodecMessage', withUnknown)
            as Map<String, Object?>;
    expect(decoded['int32Value'], 7);
    expect(decoded['mode'], 99);
  });

  test('reports exact paths for invalid bytes and oneof values', () {
    expect(
      () => codec.encode('devroute.phase5.test.CodecMessage', <String, Object?>{
        'bytesValue': 'not-base64!',
      }),
      throwsA(
        isA<Exception>().having(
          (error) => error.toString(),
          'path',
          contains('request.bytesValue'),
        ),
      ),
    );
    expect(
      () => codec.encode('devroute.phase5.test.CodecMessage', <String, Object?>{
        'first': 'a',
        'second': 2,
      }),
      throwsA(isA<Exception>()),
    );
  });

  test('round-trips supported well-known JSON mappings', () {
    final input = <String, Object?>{
      'timestamp': '2026-07-27T12:34:56.123456Z',
      'duration': '12.345s',
      'empty': <String, Object?>{},
      'structValue': <String, Object?>{
        'name': 'value',
        'count': 2.0,
        'nested': <String, Object?>{'enabled': true},
      },
      'value': <Object?>['a', 2, null],
      'listValue': <Object?>[true, 'text'],
      'fieldMask': 'profile.name,profile.email',
      'stringWrapper': 'wrapped',
      'int64Wrapper': '9007199254740992',
      'boolWrapper': true,
      'anyValue': <String, Object?>{
        '@type': 'type.googleapis.com/devroute.phase5.test.NestedValue',
        'value': <String, Object?>{'name': 'inside-any'},
      },
    };
    final bytes = codec.encode('devroute.phase5.test.WellKnownMessage', input);
    final decoded =
        codec.decode('devroute.phase5.test.WellKnownMessage', bytes)
            as Map<String, Object?>;

    expect(decoded['timestamp'], '2026-07-27T12:34:56.123456Z');
    expect(decoded['duration'], '12.345s');
    expect(decoded['structValue'], input['structValue']);
    expect(decoded['value'], input['value']);
    expect(decoded['listValue'], input['listValue']);
    expect(decoded['fieldMask'], input['fieldMask']);
    expect(decoded['stringWrapper'], 'wrapped');
    expect(decoded['int64Wrapper'], '9007199254740992');
    expect(decoded['boolWrapper'], true);
    expect(decoded['anyValue'], <String, Object?>{
      '@type': 'type.googleapis.com/devroute.phase5.test.NestedValue',
      'value': <String, Object?>{'name': 'inside-any'},
    });
  });

  test(
    'decoded nested, repeated and map runtime secrets are masked by value',
    () {
      const secret = 'nested-runtime-secret';
      final bytes = codec.encode(
        'devroute.phase5.test.CodecMessage',
        <String, Object?>{
          'nested': <String, Object?>{'name': secret},
          'reflectedValues': <String>['safe', secret],
          'reflectedLabels': <String, String>{'ordinary': secret},
        },
      );
      final decoded = codec.decode('devroute.phase5.test.CodecMessage', bytes);
      final sanitized = SecretMasker.redactStructured(
        decoded,
        runtimeSecrets: const <String>[secret],
      );
      expect(sanitized.toString(), isNot(contains(secret)));
      expect(sanitized.toString(), contains('[REDACTED]'));
    },
  );
}
